# Path where the ntuples are saved
ntuple_path: &ntuple_path /work/ws/nemo/fr_af1100-Training-Simulations-0/ntuples_p3985/

# Path where the hybrid samples will be saved
sample_path: &sample_path /work/ws/nemo/fr_af1100-Training-Simulations-0/hybrids/

# Path where the merged and ready-to-train samples are saved
file_path: &file_path /work/ws/nemo/fr_af1100-Training-Simulations-0/preprocessed/

# Name of the output file from the preprocessing
.outfile_name: &outfile_name /work/ws/nemo/fr_af1100-Training-Simulations-0/preprocessed/PFlow-hybrid.h5

# Dictfile for the scaling and shifting (json)
.dict_file: &dict_file /home/fr/fr_fr/fr_af1100/b-Tagging/scale_dicts/PFlow-scale_dict-22M.json
