# set to true if taus are to be included in preprocessing
# set to true if extended flavour labelling is used in preprocessing
outfile_name: Null
plot_name: Null
cuts: Null
dict_file: Null
var_file: Null
preparation:
  ntuples: Null
  samples: Null

sampling:
  method: Null
  options: Null
