# set to true if taus are to be included in preprocessing
# set to true if extended flavour labelling is used in preprocessing
outfile_name: Null
plot_name: Null
plot_sample_label: "$\\sqrt{s}=13$ TeV, PFlow jets"
legend_sample_category: False
dict_file: Null
var_file: Null
compression: Null
precision: Null
concat_jet_tracks: False
convert_to_tfrecord: Null
preparation:
  ntuples: Null
  samples: Null

sampling:
  method: Null
  options: Null
